site_name: AcronisFSS
site_description: Documentation for AcronisFSS
site_author: Strasser, Joel;
site_url: https://acronisfss.joestr.or.at/unspecified

repo_name: AcronisFSS-website
repo_url: https://github.com/joestrhq/AcronisFSS-website
edit_uri: http://github.com/joestrhq/AcronisFSS-website/edit/master/src/doc/docs

copyright: Copyright &copy; joestr.or.at and all contributors

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - About: about.md
theme:
  name: material
